trigger:
  - main

pool:
  default

jobs:
  - job: Build
    displayName: 'Build job'
    steps:
      - task: UseDotNet@2
        inputs:
          version: '3.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - script: dotnet build --configuration Release
        displayName: 'Build the project'

  - job: Deploy
    displayName: 'Deploy job'
    dependsOn: Build
    steps:
      - task: UseDotNet@2
        inputs:
          version: '3.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
        displayName: 'Publish the project'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'

  - job: WarmUp
    displayName: 'Warm up the website'
    dependsOn: Deploy
    steps:
      - powershell: |
          $url = "https://mywebsitecyrus.azurewebsites.net/"
          Invoke-WebRequest -Uri $url -UseBasicParsing
        displayName: 'Send HTTP request to warm up the website'